### ISSUE TITLE
set language 

### ISSUE THREAD

**Issue by fivemNoobDev** [morethancodenl/mtc-moneywash#2]
where do i set the language?

**Comment by NietThijmen** [comment]
Hi!

You can setup your language in the [fxmanifest](https://github.com/morethancodenl/mtc-moneywash/blob/2db8b58bd0a3f66b9830bd1ed62c94bdb75bf891/fxmanifest.lua#L14)

**Comment by fivemNoobDev** [comment]
![image](https://github.com/morethancodenl/mtc-moneywash/assets/153878827/f39a409f-75cb-49c5-b293-c24c4ea26b76)
where at exactly?

**Comment by NietThijmen** [comment]
locale/nl.lua

**Comment by fivemNoobDev** [comment]
nevermind thank you!!

**Comment by fivemNoobDev** [comment]
everytime i change it to locale/en.lua i get errors

**Comment by fivemNoobDev** [comment]
![Screenshot 2023-12-17 161427](https://github.com/morethancodenl/mtc-moneywash/assets/153878827/43f8aee9-f814-48a5-9bd1-4d4349e928b1)

**Comment by NietThijmen** [comment]
Have you already restarted your server?

**Comment by fivemNoobDev** [comment]
have not restarted let me try

**Comment by fivemNoobDev** [comment]
that worked sorry  lmao
